import { StoryFn, Meta } from '@storybook/react';
import { TableHeaderTextProps } from './TableHeaderText';
declare const _default: Meta;
export default _default;
export declare const Basic: StoryFn<TableHeaderTextProps>;
export declare const Disabled: StoryFn<TableHeaderTextProps>;
export declare const HelpCircle: StoryFn<TableHeaderTextProps>;
export declare const ArrowUp: StoryFn<TableHeaderTextProps>;
export declare const ArrowDown: StoryFn<TableHeaderTextProps>;
export declare const ArrowUpHelpCircle: StoryFn<TableHeaderTextProps>;
export declare const ArrowDownHelpCircle: StoryFn<TableHeaderTextProps>;
